---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime
  labels:
    app: amazon-prime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-prime
  template:
    metadata:
      labels:
        app: amazon-prime
    spec:
      containers:
      - name: amazon-prime
        image: isma3elovic:prime
        ports:
        - containerPort: 3000
...
